### ISSUE TITLE
Infinite Flight Dutch Translation

### ISSUE THREAD

**Issue by EmielIF** [flyingdevelopmentstudio/infiniteflight-localization#24]
**What language do you wish to contribute?**

I would like to translate the Infinite Flight app to Dutch. A language spoken mainly in the Netherlands, but also northern part of Belgium, aswell as a couple of islands in the Caribbean.

**Comment by carmichaelalonso** [comment]
Hey! Thanks for offering to contribute

Just to be transparent about our current focus, it is currently on languages where the local speakers do not understand English well. 

The reason I'm saying this is because we have had a translator recently start translating Dutch, but once he started, we realised it may not be worth it because most Dutch people speak fluent English (90-93% from what I have seen). It made it hard to translate technical words because they sound better in English :)

We aren't prioritizing a Dutch translation at this time because of this, but let us know if you believe it is a different case. Thanks regardless for the kind offer!
